---
- name: Install and start httpd
  hosts: web
  tasks:
    - name: Install httpd
      become: true
      ansible.builtin.package:
        name: httpd
        state: present
    - name: Start httpd
      ansible.builtin.service:
        name: httpd
        state: started
      become: true
