---
- name: Install missing package and restart service
  hosts: all
  become: true
  tasks:
    - name: Install missing package
      community.general.npm:
        name: package_name
        path: /var/app/nodeapi
    - name: restart service
      ansible.builtin.service:
        name: node-api.service
        state: restarted
