---
- name: Install missing package and restart service
  hosts: all
  become: true
  tasks:
    - name: Install express package
      community.general.npm:
        name: express
        path: /var/app/nodeapi
    - name: restart node-api.service
      ansible.builtin.service:
        name: node-api.service
        state: restarted
